package loader

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// getCallerDir attempts to find the directory of the original source file (e.g. main.go)
// by traversing the call stack and skipping known library paths.
// This provides an extremely robust anchor for 'go run' where os.Executable is in /tmp/.
func getCallerDir() string {
	for i := 1; i < 25; i++ {
		_, file, _, ok := runtime.Caller(i)
		if !ok {
			break
		}
		// Skip list: stdlib and platform internal libs
		skip := false
		libsToSkip := []string{
			"runtime/", "reflect/", "testing/",
			"distributed-config", "microservice-toolbox", "universal-logger",
			"flexible-logger", "safe-socket", "message-serializers",
			"<autogenerated>",
		}
		for _, lib := range libsToSkip {
			if strings.Contains(file, lib) {
				skip = true
				break
			}
		}

		if !skip && file != "" {
			return filepath.Dir(file)
		}
	}
	return ""
}

// ResolveConfigPath handles the search logic for configuration files.
// It searches only for the targetName profile config in the binary directory (or caller source) and CWD.
//
// SEARCH ORDER (Locality First):
// 1. EXE/[targetName].yaml
// 2. CWD/[targetName].yaml
// -----------------------------------------------------------------------------

func ResolveConfigPath(targetName string) string {
	// 1. Determine Executable Context
	exePath, err := os.Executable()
	exeDir := ""
	if err == nil {
		exePathAbs, _ := filepath.Abs(exePath)
		exeDir = filepath.Dir(exePathAbs)
	}

	// 2. Smart Resolve for 'go run': find the directory of the caller's main.go
	if exeDir == "" || strings.Contains(exeDir, "go-build") || strings.Contains(exeDir, "T/go-build") {
		if callerDir := getCallerDir(); callerDir != "" {
			exeDir = callerDir
		}
	}

	cwd, _ := os.Getwd()

	// 3. Build Search Candidates (STRICT ORDER: Binary directory first)
	var candidates []string

	// Local to Binary (Priority 1)
	if targetName != "" && exeDir != "" {
		candidates = append(candidates, filepath.Join(exeDir, targetName+".yaml"))
	}

	// Local to CWD (Priority 2)
	if targetName != "" && cwd != "" && cwd != exeDir {
		candidates = append(candidates, filepath.Join(cwd, targetName+".yaml"))
	}

	// 4. Search Loop
	for _, path := range candidates {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	// 5. Default Fallback
	baseDir := exeDir
	if baseDir == "" {
		baseDir = cwd
	}

	if targetName != "" {
		if baseDir != "" {
			return filepath.Join(baseDir, targetName+".yaml")
		}
		return targetName + ".yaml"
	}

	if baseDir != "" {
		return filepath.Join(baseDir, "config.yaml")
	}
	return "config.yaml"
}
