// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: src/schemas/config.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMsg_ConfigClientCmd int32

const (
	ConfigMsg_update_mem_config     ConfigMsg_ConfigClientCmd = 0
	ConfigMsg_update_config_object  ConfigMsg_ConfigClientCmd = 1
	ConfigMsg_get_mem_config        ConfigMsg_ConfigClientCmd = 2
	ConfigMsg_get_config_object     ConfigMsg_ConfigClientCmd = 3
	ConfigMsg_add_config_listener   ConfigMsg_ConfigClientCmd = 4
	ConfigMsg_dump_mem_config       ConfigMsg_ConfigClientCmd = 5
	ConfigMsg_get_notif_loglevel    ConfigMsg_ConfigClientCmd = 6
	ConfigMsg_update_notif_loglevel ConfigMsg_ConfigClientCmd = 7
)

// Enum value maps for ConfigMsg_ConfigClientCmd.
var (
	ConfigMsg_ConfigClientCmd_name = map[int32]string{
		0: "update_mem_config",
		1: "update_config_object",
		2: "get_mem_config",
		3: "get_config_object",
		4: "add_config_listener",
		5: "dump_mem_config",
		6: "get_notif_loglevel",
		7: "update_notif_loglevel",
	}
	ConfigMsg_ConfigClientCmd_value = map[string]int32{
		"update_mem_config":     0,
		"update_config_object":  1,
		"get_mem_config":        2,
		"get_config_object":     3,
		"add_config_listener":   4,
		"dump_mem_config":       5,
		"get_notif_loglevel":    6,
		"update_notif_loglevel": 7,
	}
)

func (x ConfigMsg_ConfigClientCmd) Enum() *ConfigMsg_ConfigClientCmd {
	p := new(ConfigMsg_ConfigClientCmd)
	*p = x
	return p
}

func (x ConfigMsg_ConfigClientCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigMsg_ConfigClientCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_src_schemas_config_proto_enumTypes[0].Descriptor()
}

func (ConfigMsg_ConfigClientCmd) Type() protoreflect.EnumType {
	return &file_src_schemas_config_proto_enumTypes[0]
}

func (x ConfigMsg_ConfigClientCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigMsg_ConfigClientCmd.Descriptor instead.
func (ConfigMsg_ConfigClientCmd) EnumDescriptor() ([]byte, []int) {
	return file_src_schemas_config_proto_rawDescGZIP(), []int{0, 0}
}

type ConfigMsg_ConfigServerMsg int32

const (
	ConfigMsg_propagate_mem_config     ConfigMsg_ConfigServerMsg = 0
	ConfigMsg_mem_config_update_done   ConfigMsg_ConfigServerMsg = 1
	ConfigMsg_propagate_config         ConfigMsg_ConfigServerMsg = 2
	ConfigMsg_config_update_done       ConfigMsg_ConfigServerMsg = 3
	ConfigMsg_mem_config_update_failed ConfigMsg_ConfigServerMsg = 4
	ConfigMsg_config_update_failed     ConfigMsg_ConfigServerMsg = 5
	ConfigMsg_propagate_notif_loglevel ConfigMsg_ConfigServerMsg = 6
	ConfigMsg_send_config_init         ConfigMsg_ConfigServerMsg = 7
	ConfigMsg_send_mem_config_init     ConfigMsg_ConfigServerMsg = 8
	ConfigMsg_send_notif_loglevel_init ConfigMsg_ConfigServerMsg = 9
)

// Enum value maps for ConfigMsg_ConfigServerMsg.
var (
	ConfigMsg_ConfigServerMsg_name = map[int32]string{
		0: "propagate_mem_config",
		1: "mem_config_update_done",
		2: "propagate_config",
		3: "config_update_done",
		4: "mem_config_update_failed",
		5: "config_update_failed",
		6: "propagate_notif_loglevel",
		7: "send_config_init",
		8: "send_mem_config_init",
		9: "send_notif_loglevel_init",
	}
	ConfigMsg_ConfigServerMsg_value = map[string]int32{
		"propagate_mem_config":     0,
		"mem_config_update_done":   1,
		"propagate_config":         2,
		"config_update_done":       3,
		"mem_config_update_failed": 4,
		"config_update_failed":     5,
		"propagate_notif_loglevel": 6,
		"send_config_init":         7,
		"send_mem_config_init":     8,
		"send_notif_loglevel_init": 9,
	}
)

func (x ConfigMsg_ConfigServerMsg) Enum() *ConfigMsg_ConfigServerMsg {
	p := new(ConfigMsg_ConfigServerMsg)
	*p = x
	return p
}

func (x ConfigMsg_ConfigServerMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigMsg_ConfigServerMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_src_schemas_config_proto_enumTypes[1].Descriptor()
}

func (ConfigMsg_ConfigServerMsg) Type() protoreflect.EnumType {
	return &file_src_schemas_config_proto_enumTypes[1]
}

func (x ConfigMsg_ConfigServerMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigMsg_ConfigServerMsg.Descriptor instead.
func (ConfigMsg_ConfigServerMsg) EnumDescriptor() ([]byte, []int) {
	return file_src_schemas_config_proto_rawDescGZIP(), []int{0, 1}
}

type ConfigMsg struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	ReqClient          ConfigMsg_ConfigClientCmd `protobuf:"varint,1,opt,name=ReqClient,proto3,enum=config.ConfigMsg_ConfigClientCmd" json:"ReqClient,omitempty"`
	SectionsKeysValues map[string]*KeysValues    `protobuf:"bytes,2,rep,name=SectionsKeysValues,proto3" json:"SectionsKeysValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RespServer         ConfigMsg_ConfigServerMsg `protobuf:"varint,3,opt,name=RespServer,proto3,enum=config.ConfigMsg_ConfigServerMsg" json:"RespServer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigMsg) Reset() {
	*x = ConfigMsg{}
	mi := &file_src_schemas_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMsg) ProtoMessage() {}

func (x *ConfigMsg) ProtoReflect() protoreflect.Message {
	mi := &file_src_schemas_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMsg.ProtoReflect.Descriptor instead.
func (*ConfigMsg) Descriptor() ([]byte, []int) {
	return file_src_schemas_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMsg) GetReqClient() ConfigMsg_ConfigClientCmd {
	if x != nil {
		return x.ReqClient
	}
	return ConfigMsg_update_mem_config
}

func (x *ConfigMsg) GetSectionsKeysValues() map[string]*KeysValues {
	if x != nil {
		return x.SectionsKeysValues
	}
	return nil
}

func (x *ConfigMsg) GetRespServer() ConfigMsg_ConfigServerMsg {
	if x != nil {
		return x.RespServer
	}
	return ConfigMsg_propagate_mem_config
}

type KeysValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValue      map[string]string      `protobuf:"bytes,1,rep,name=KeyValue,proto3" json:"KeyValue,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysValues) Reset() {
	*x = KeysValues{}
	mi := &file_src_schemas_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysValues) ProtoMessage() {}

func (x *KeysValues) ProtoReflect() protoreflect.Message {
	mi := &file_src_schemas_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysValues.ProtoReflect.Descriptor instead.
func (*KeysValues) Descriptor() ([]byte, []int) {
	return file_src_schemas_config_proto_rawDescGZIP(), []int{1}
}

func (x *KeysValues) GetKeyValue() map[string]string {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

var File_src_schemas_config_proto protoreflect.FileDescriptor

const file_src_schemas_config_proto_rawDesc = "" +
	"\n" +
	"\x18src/schemas/config.proto\x12\x06config\"\xb2\x06\n" +
	"\tConfigMsg\x12?\n" +
	"\tReqClient\x18\x01 \x01(\x0e2!.config.ConfigMsg.ConfigClientCmdR\tReqClient\x12Y\n" +
	"\x12SectionsKeysValues\x18\x02 \x03(\v2).config.ConfigMsg.SectionsKeysValuesEntryR\x12SectionsKeysValues\x12A\n" +
	"\n" +
	"RespServer\x18\x03 \x01(\x0e2!.config.ConfigMsg.ConfigServerMsgR\n" +
	"RespServer\x1aY\n" +
	"\x17SectionsKeysValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.config.KeysValuesR\x05value:\x028\x01\"\xce\x01\n" +
	"\x0fConfigClientCmd\x12\x15\n" +
	"\x11update_mem_config\x10\x00\x12\x18\n" +
	"\x14update_config_object\x10\x01\x12\x12\n" +
	"\x0eget_mem_config\x10\x02\x12\x15\n" +
	"\x11get_config_object\x10\x03\x12\x17\n" +
	"\x13add_config_listener\x10\x04\x12\x13\n" +
	"\x0fdump_mem_config\x10\x05\x12\x16\n" +
	"\x12get_notif_loglevel\x10\x06\x12\x19\n" +
	"\x15update_notif_loglevel\x10\a\"\x99\x02\n" +
	"\x0fConfigServerMsg\x12\x18\n" +
	"\x14propagate_mem_config\x10\x00\x12\x1a\n" +
	"\x16mem_config_update_done\x10\x01\x12\x14\n" +
	"\x10propagate_config\x10\x02\x12\x16\n" +
	"\x12config_update_done\x10\x03\x12\x1c\n" +
	"\x18mem_config_update_failed\x10\x04\x12\x18\n" +
	"\x14config_update_failed\x10\x05\x12\x1c\n" +
	"\x18propagate_notif_loglevel\x10\x06\x12\x14\n" +
	"\x10send_config_init\x10\a\x12\x18\n" +
	"\x14send_mem_config_init\x10\b\x12\x1c\n" +
	"\x18send_notif_loglevel_init\x10\t\"\x87\x01\n" +
	"\n" +
	"KeysValues\x12<\n" +
	"\bKeyValue\x18\x01 \x03(\v2 .config.KeysValues.KeyValueEntryR\bKeyValue\x1a;\n" +
	"\rKeyValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=github.com/Bastien-Antigravity/distributed-config/src/schemasb\x06proto3"

var (
	file_src_schemas_config_proto_rawDescOnce sync.Once
	file_src_schemas_config_proto_rawDescData []byte
)

func file_src_schemas_config_proto_rawDescGZIP() []byte {
	file_src_schemas_config_proto_rawDescOnce.Do(func() {
		file_src_schemas_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_schemas_config_proto_rawDesc), len(file_src_schemas_config_proto_rawDesc)))
	})
	return file_src_schemas_config_proto_rawDescData
}

var file_src_schemas_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_schemas_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_schemas_config_proto_goTypes = []any{
	(ConfigMsg_ConfigClientCmd)(0), // 0: config.ConfigMsg.ConfigClientCmd
	(ConfigMsg_ConfigServerMsg)(0), // 1: config.ConfigMsg.ConfigServerMsg
	(*ConfigMsg)(nil),              // 2: config.ConfigMsg
	(*KeysValues)(nil),             // 3: config.KeysValues
	nil,                            // 4: config.ConfigMsg.SectionsKeysValuesEntry
	nil,                            // 5: config.KeysValues.KeyValueEntry
}
var file_src_schemas_config_proto_depIdxs = []int32{
	0, // 0: config.ConfigMsg.ReqClient:type_name -> config.ConfigMsg.ConfigClientCmd
	4, // 1: config.ConfigMsg.SectionsKeysValues:type_name -> config.ConfigMsg.SectionsKeysValuesEntry
	1, // 2: config.ConfigMsg.RespServer:type_name -> config.ConfigMsg.ConfigServerMsg
	5, // 3: config.KeysValues.KeyValue:type_name -> config.KeysValues.KeyValueEntry
	3, // 4: config.ConfigMsg.SectionsKeysValuesEntry.value:type_name -> config.KeysValues
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_src_schemas_config_proto_init() }
func file_src_schemas_config_proto_init() {
	if File_src_schemas_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_schemas_config_proto_rawDesc), len(file_src_schemas_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_schemas_config_proto_goTypes,
		DependencyIndexes: file_src_schemas_config_proto_depIdxs,
		EnumInfos:         file_src_schemas_config_proto_enumTypes,
		MessageInfos:      file_src_schemas_config_proto_msgTypes,
	}.Build()
	File_src_schemas_config_proto = out.File
	file_src_schemas_config_proto_goTypes = nil
	file_src_schemas_config_proto_depIdxs = nil
}
