// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: config.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMsg_Cmd int32

const (
	ConfigMsg_GET_SYNC           ConfigMsg_Cmd = 0
	ConfigMsg_PUT_SYNC           ConfigMsg_Cmd = 1
	ConfigMsg_BROADCAST_SYNC     ConfigMsg_Cmd = 2
	ConfigMsg_ACK                ConfigMsg_Cmd = 3
	ConfigMsg_ERROR              ConfigMsg_Cmd = 4
	ConfigMsg_BROADCAST_REGISTRY ConfigMsg_Cmd = 5
)

// Enum value maps for ConfigMsg_Cmd.
var (
	ConfigMsg_Cmd_name = map[int32]string{
		0: "GET_SYNC",
		1: "PUT_SYNC",
		2: "BROADCAST_SYNC",
		3: "ACK",
		4: "ERROR",
		5: "BROADCAST_REGISTRY",
	}
	ConfigMsg_Cmd_value = map[string]int32{
		"GET_SYNC":           0,
		"PUT_SYNC":           1,
		"BROADCAST_SYNC":     2,
		"ACK":                3,
		"ERROR":              4,
		"BROADCAST_REGISTRY": 5,
	}
)

func (x ConfigMsg_Cmd) Enum() *ConfigMsg_Cmd {
	p := new(ConfigMsg_Cmd)
	*p = x
	return p
}

func (x ConfigMsg_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigMsg_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (ConfigMsg_Cmd) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x ConfigMsg_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigMsg_Cmd.Descriptor instead.
func (ConfigMsg_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

type ConfigMsg struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command ConfigMsg_Cmd          `protobuf:"varint,1,opt,name=Command,proto3,enum=config.ConfigMsg_Cmd" json:"Command,omitempty"`
	// JSON encoded payload representing either the ConfigMap or the ServiceRegistry.
	// This removes the need for infinite Protobuf model coupling.
	Payload       []byte `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMsg) Reset() {
	*x = ConfigMsg{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMsg) ProtoMessage() {}

func (x *ConfigMsg) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMsg.ProtoReflect.Descriptor instead.
func (*ConfigMsg) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMsg) GetCommand() ConfigMsg_Cmd {
	if x != nil {
		return x.Command
	}
	return ConfigMsg_GET_SYNC
}

func (x *ConfigMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\"\xb9\x01\n" +
	"\tConfigMsg\x12/\n" +
	"\aCommand\x18\x01 \x01(\x0e2\x15.config.ConfigMsg.CmdR\aCommand\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\aPayload\"a\n" +
	"\x03Cmd\x12\f\n" +
	"\bGET_SYNC\x10\x00\x12\f\n" +
	"\bPUT_SYNC\x10\x01\x12\x12\n" +
	"\x0eBROADCAST_SYNC\x10\x02\x12\a\n" +
	"\x03ACK\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\x16\n" +
	"\x12BROADCAST_REGISTRY\x10\x05B?Z=github.com/Bastien-Antigravity/distributed-config/src/schemasb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_proto_goTypes = []any{
	(ConfigMsg_Cmd)(0), // 0: config.ConfigMsg.Cmd
	(*ConfigMsg)(nil),  // 1: config.ConfigMsg
}
var file_config_proto_depIdxs = []int32{
	0, // 0: config.ConfigMsg.Command:type_name -> config.ConfigMsg.Cmd
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
